sudo: false
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - pip install tox-travis
  - pip install codecov
  - pip install -r requirements.txt


script:
  - make lint
  - make test-all

after_success:
  - codecov --token=avm4PQNy8UecTz8q631p

deploy:
    provider: pypi
    user: pm3310
    password:
        secure: YZlYQhzzVGL9Jyi1bNOUblQN2E541qizLhSS9VwMiZG25Z8uMbiOA7Al4idJuixYwO5wN4MPW+IciXbQKOfVCm2ZUNfV7Lml2pm5MlS3HAaTC9+saUrLBXmAL3AZ8JfodDEBh6B7aBRGJ8Bq4rsfzxnJtgpGXdYIDvKWSQOFSQ9Xh35KNoNdOzY6bczfU8L9vRKJhYmKgCxmwqbZvBi8g4dIO6hdv7pM19TJb5C9bE3yrj7h49eZ72OIWYWZcvVNSt9A5LakJTTh81T8avWdUGaEeoWwtd3/CV/L3eg10VIjpAoWtv1G4XN5oB/N7B9YfYHQj0MqQQNFYOvDyu+iPBRmpP9ZOFAuDU4/EpqcEM64CTbhPMjq9aM0HrjmIdffGu5pGX7qIehChtnpcwM33qMS40HCO1Y7KGLjo3BN8T3KW312H3rVgZfhWGmMmz0BL8zxvp4ucYlBnULe23UXynr8QAqYwAuZhhsBhgyj73Pte0pp3RwkRxujco6xrRK+BoxJtHJQ6V/MSqwa5/NEVFOCuKTUYifw007nb5b3ThxVpRO9wVTTRuyk0bJHMXNL6UeQbmw/TG8wtsoTrlKj68yanWO8f1q/V8iQFX44jLVNwgPvSp5P8gRCkY1mkk9dokM0xYLSm85Yk5LzQEISjGsbW7gqRG0CNsyuX0prTB0=
    on:
        branch: master
